* Emacs Twist for Nix
Emacs Twist is an alternative Emacs Lisp build machinery for Nix.

The goal of this project is to support the following two use cases:

- Let people manage their Emacs configurations using Nix, in a reproducible but much more configurable manner than the Nix wrapper combined with [[https://github.com/nix-community/emacs-overlay][emacs-overlay]].
- Help with testing of Emacs Lisp packages that have difficult dependencies, such as dynamic libraries and Emacs Lisp packages that are not on any package registry.

At present, the former use case is almost supported.
It is being actively developed to ensure that it can build existing live configurations.
The documentation will become available at some point during the phase.

The latter use case is secondary, and I have not started working on it yet.

It is still an alpha version, so there may be breaking changes.
** Examples
I am preparing [[https://github.com/akirak/emacs-twist-examples][a repository of configuration examples]].
