* Emacs Twist for Nix
[[https://github.com/akirak/emacs-twist/actions/workflows/test.yml][file:https://github.com/akirak/emacs-twist/actions/workflows/test.yml/badge.svg]]

Emacs Twist is an alternative Emacs Lisp build machinery for Nix.

The goal of this project is to support the following two use cases:

- Let people manage their Emacs configurations using Nix, in a reproducible but more contributor-friendly way than the standard Emacs infrastructure of Nixpkgs.
- Help with testing of Emacs Lisp packages that have difficult dependencies, such as dynamic libraries and Emacs Lisp packages that are not on any package registry.

I am currently working on the first use case to ensure that it can build existing live configurations.
The documentation will become available at some point during the phase.

The latter use case is secondary, and I have not started working on it yet.

It is still an alpha version, so there may be breaking changes.

Note that this framework is not compatible with [[https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/emacs/generic.nix][the Emacs infrastructure]] of Nixpkgs.
This repository provides the core library, and it should be stable.
I don't want to constantly follow updates in the Nixpkgs and [[https://github.com/nix-community/emacs-overlay][emacs-overlay]].
They are great projects, but this project does not reuse the infrastructure.
An entire infrastructure was written from scratch, and this would allow keeping each configuration explicit and predictable.
No package workarounds are turned on by default, nor will I include such things in this repository.

Nonetheless, it would be possible to provide workarounds as an overlay from a separate repository.
If this project turns out to be viable, I will do that.
** Related projects
[[https://github.com/akirak/twist.el][Twist.el]] is a work-in-progress Emacs frontend to Twist.
** Examples
- I am preparing [[https://github.com/akirak/emacs-twist-examples][a repository of configuration examples]].
- The author's [[https://github.com/akirak/nix-config][nix-config]] repository uses Twist.
